export const estados = [
    { estado: 'AGUASCALIENTES', value: 'aguascalientes' },
    { estado: 'BAJA CALIFORNIA', value: 'baja_california' },
    { estado: 'BAJA CALIFORNIA SUR', value: 'baja_california_sur' },
    { estado: 'CAMPECHE', value: 'campeche' },
    { estado: 'CHIAPAS', value: 'chiapas' },
    { estado: 'CHIHUAHUA', value: 'chihuahua' },
    { estado: 'CIUDAD DE MÉXICO', value: 'ciudad_de_mexico' },
    { estado: 'COAHUILA', value: 'coahuila' },
    { estado: 'COLIMA', value: 'colima' },
    { estado: 'DURANGO', value: 'durango' },
    { estado: 'GUANAJUATO', value: 'guanajuato' },
    { estado: 'GUERRERO', value: 'guerrero' },
    { estado: 'HIDALGO', value: 'hidalgo' },
    { estado: 'JALISCO', value: 'jalisco' },
    { estado: 'MÉXICO', value: 'mexico' },
    { estado: 'MICHOACÁN', value: 'michoacan' },
    { estado: 'MORELOS', value: 'morelos' },
    { estado: 'NAYARIT', value: 'nayarit' },
    { estado: 'NUEVO LEÓN', value: 'nuevo_leon' },
    { estado: 'OAXACA', value: 'oaxaca' },
    { estado: 'PUEBLA', value: 'puebla' },
    { estado: 'QUERÉTARO', value: 'queretaro' },
    { estado: 'QUINTANA ROO', value: 'quintana_roo' },
    { estado: 'SAN LUIS POTOSÍ', value: 'san_luis_potosi' },
    { estado: 'SINALOA', value: 'sinaloa' },
    { estado: 'SONORA', value: 'sonora' },
    { estado: 'TABASCO', value: 'tabasco' },
    { estado: 'TAMAULIPAS', value: 'tamaulipas' },
    { estado: 'TLAXCALA', value: 'tlaxcala' },
    { estado: 'VERACRUZ', value: 'veracruz' },
    { estado: 'YUCATÁN', value: 'yucatan' },
    { estado: 'ZACATECAS', value: 'zacatecas' }
];
